# file: pyproject.toml
[project]
name = "code-to-pdf"
version = "0.1.0"
dependencies = [
  "pathspec>=0.12",
  "binaryornot>=0.4",
  "pygments>=2.16",
  "weasyprint>=62",
]

[project.scripts]
code2pdf = "code_to_pdf.cli:main"